### ISSUE TITLE
"selected" items do not get selected

### ISSUE THREAD

**Issue by toastbrotch** [RyanFitzgerald/tagselector#1]
hi Ryan

i love the simplicity of your lib. 
only one feature is missing (or maybe its a bug?) if i have an option "selected" and this is not going to be styled as select after loading your lib.
in your example:
`	<option value="opel" selected>Opel</option>`

can you reproduce?

thanx a lot in advance and cheers
ivo

**Comment by RyanFitzgerald** [comment]
Hi,

Thanks for pointing it out, it was definitely a bug! I have fixed it and pushed the changes. If you grab the latest JS, it should be good to go. Please let me know if there are still any issues.

Thanks,

Ryan

**Comment by toastbrotch** [comment]
thanx a lot, it's working!
